### ISSUE TITLE
System.PlatformNotSupportedException: Named maps are not supported.

### ISSUE THREAD

**Issue by megahirt** [sillsdev/LfMerge#317]
Putting project 'orm-ec-flex' on hold due to unhandled exception:

System.PlatformNotSupportedException: Named maps are not supported.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(FileStream fileStream, String mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen(String mapName, Int64 capacity)
   at SIL.LCModel.Infrastructure.Impl.SharedXMLBackendProvider.CreateOrOpen(String name, Int64 capacity, Boolean createdNew)
   at SIL.LCModel.Infrastructure.Impl.SharedXMLBackendProvider.CreateSharedMemory(Boolean createdNew)
   at SIL.LCModel.Infrastructure.Impl.SharedXMLBackendProvider.StartupInternal(Int32 currentModelVersion)
   at SIL.LCModel.Infrastructure.Impl.BackendProvider.StartupInternalWithDataMigrationIfNeeded(IThreadedProgress progressDlg)
   at SIL.LCModel.Infrastructure.Impl.BackendProvider.StartupExtantLanguageProject(IProjectIdentifier projectId, Boolean fBootstrapSystem, IThreadedProgress progressDlg)
   at SIL.LCModel.LcmCache.<>c__DisplayClass12_0.<CreateCacheFromExistingData>b__0(IDataSetup dataSetup)
   at SIL.LCModel.LcmCache.CreateCacheInternal(IProjectIdentifier projectId, String userWsIcuLocale, ILcmUI ui, ILcmDirectories dirs, LcmSettings settings, Action`1 doThe, Action`1 initialize)
   at SIL.LCModel.LcmCache.CreateCacheFromExistingData(IProjectIdentifier projectId, String userWsIcuLocale, ILcmUI ui, ILcmDirectories dirs, LcmSettings settings, IThreadedProgress progressDlg)
   at LfMerge.Core.FieldWorks.FwProject.TryGetLcmCache() in /home/builder/repo/src/LfMerge.Core/FieldWorks/FwProject.cs:line 97
   at LfMerge.Core.FieldWorks.FwProject..ctor(LfMergeSettings settings, String database) in /home/builder/repo/src/LfMerge.Core/FieldWorks/FwProject.cs:line 31
   at LfMerge.Core.LanguageForgeProject.get_FieldWorksProject() in /home/builder/repo/src/LfMerge.Core/LanguageForgeProject.cs:line 93
   at LfMerge.Core.Actions.TransferLcmToMongoAction.DoRun(ILfProject project) in /home/builder/repo/src/LfMerge.Core/Actions/TransferLcmToMongoAction.cs:line 44
   at LfMerge.Core.Actions.Action.Run(ILfProject project) in /home/builder/repo/src/LfMerge.Core

**Comment by megahirt** [comment]
User reported that project `aeb-ar-flex` now also suffers from the same exception. :(

**Comment by megahirt** [comment]
A few internet references:

https://github.com/dotnet/runtime/issues/21863
https://learn.microsoft.com/en-us/answers/questions/299628/creating-memorymappedfile-fails-with-platformnotsu.html?childToView=301869#comment-301869
https://robertwray.co.uk/blog/reading-and-writing-a-memory-mapped-file-in-net-core

In short, the line
```
System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen(String mapName, Int64 capacity)
```

**Comment by jasonleenaylor** [comment]
To help understand when and why this will affect your users LCM will use the SharedXMLBackendProvider when the settings for the project enables sharing on the local system, or when the FieldWorks project has imported scripture (which indicates that sharing with Paratext is desired/enabled)

**Comment by megahirt** [comment]
> To help understand when and why this will affect your users LCM will use the SharedXMLBackendProvider when the settings for the project enables sharing on the local system, or when the FieldWorks project has imported scripture (which indicates that sharing with Paratext is desired/enabled)

Thank you for this explanation - makes sense to me and it also explains why most projects aren't hitting this error.  Thanks @jasonleenaylor

**Comment by longrunningprocess** [comment]
`sbe-flex` is also on HOLD because of this.

**Comment by hahn-kev** [comment]
this is still happening :( the fix in I pushed to lcm didn't fix the issue. There's a number of other places that need to be fixed too.
